/*
Created: 19/12/2017
Modified: 19/12/2017
Model: SQLite
Database: SQLite 3.7
*/


-- Create tables section -------------------------------------------------

-- Table COCHE

CREATE TABLE COCHE
(
  COCHE_ID NUMERIC NOT NULL,
  MATRICULA TEXT NOT NULL,
  MARCA TEXT NOT NULL,
  MODELO TEXT NOT NULL,
  EXTRAS TEXT,
  CILINDRADA NUMERIC NOT NULL,
  AÑO NUMERIC NOT NULL,
  NUMERO_BASTIDOR TEXT NOT NULL,
  VALOR_MERCADO NUMERIC NOT NULL,
  CONSTRAINT Key1 PRIMARY KEY (COCHE_ID),
  CONSTRAINT matricula UNIQUE (MATRICULA),
  CONSTRAINT numero_bastidor UNIQUE (NUMERO_BASTIDOR)
);

-- Table PARTE

CREATE TABLE PARTE
(
  PARTE_ID NUMERIC NOT NULL,
  CODIGO NUMERIC NOT NULL,
  FECHA NONE NOT NULL,
  COCHE_ID NUMERIC NOT NULL,
  CONSTRAINT Key2 PRIMARY KEY (PARTE_ID),
  CONSTRAINT CODIGO UNIQUE (CODIGO),
  CONSTRAINT Relationship1 FOREIGN KEY (COCHE_ID) REFERENCES COCHE (COCHE_ID)
);

CREATE INDEX IX_Relationship1 ON PARTE (COCHE_ID);

