/*
Created: 19/12/2017
Modified: 19/12/2017
Model: SQLite
Database: SQLite 3.7
*/


-- Create tables section -------------------------------------------------

-- Table COCHE

CREATE TABLE COCHE
(
  COCHE_ID INTEGER NOT NULL,
  MATRICULA TEXT NOT NULL,
  MARCA TEXT NOT NULL,
  MODELO TEXT NOT NULL,
  EXTRAS TEXT,
  CILINDRADA INTEGER NOT NULL
        CONSTRAINT CILINDRADA_MENOS10000 CHECK (CILINDRADA <10000),
  ANO INTEGER NOT NULL
        CONSTRAINT ANO_4CIFRAS CHECK (ANO < 10000 and ANO >	999),
  NUMERO_BASTIDOR TEXT NOT NULL,
  PRECIO_MERCADO INTEGER NOT NULL
        CONSTRAINT P_MERCADO_MAS100 CHECK (PRECIO_MERCADO > 100),
  CONSTRAINT ANO_4CIFRAS CHECK (ANO < 10000 and ANO >    999),
  CONSTRAINT CILINDRADA_MENOS10000 CHECK (CILINDRADA <10000),
  CONSTRAINT P_MERCADO_MAS100 CHECK (PRECIO_MERCADO > 100),
  CONSTRAINT Key1 PRIMARY KEY (COCHE_ID),
  CONSTRAINT numero_bastidor UNIQUE (NUMERO_BASTIDOR),
  CONSTRAINT matricula UNIQUE (MATRICULA)
);

-- Table PARTE

CREATE TABLE PARTE
(
  PARTE_ID INTEGER NOT NULL,
  CODIGO TEXT NOT NULL,
  FECHA TEXT NOT NULL,
  COCHE_ID INTEGER NOT NULL,
  CONSTRAINT Key2 PRIMARY KEY (PARTE_ID),
  CONSTRAINT CODIGO UNIQUE (CODIGO),
  CONSTRAINT Relationship1 FOREIGN KEY (COCHE_ID) REFERENCES COCHE (COCHE_ID)
);

CREATE INDEX IX_Relationship1 ON PARTE (COCHE_ID);

